os: Visual Studio 2017

version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration: Release

before_build:
  - nuget restore

after_build:
  # Papercut
  - cd %APPVEYOR_BUILD_FOLDER%\src\bin\Release\net452 # md plugins
  - 7z a SuperClean.%APPVEYOR_BUILD_VERSION%.zip SuperClean.exe
  - 7z a SuperClean.%APPVEYOR_BUILD_VERSION%.zip SuperClean.exe.*
  - appveyor PushArtifact SuperClean.%APPVEYOR_BUILD_VERSION%.zip